//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe.Basics.Factions.Ants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AntGeneratorFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AntGeneratorFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.Basics.Factions.Ants.AntGeneratorFiles", typeof(AntGeneratorFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaliyah
        ///Aarushi
        ///Abbey
        ///Abbi
        ///Abbie
        ///Abby
        ///Abelina
        ///Abi
        ///Abia
        ///Abigail
        ///Aby
        ///Acacia
        ///Ada
        ///Adalia
        ///Adalyn
        ///Addie
        ///Addison
        ///Adelaide
        ///Adele
        ///Adelia
        ///Adelina
        ///Adeline
        ///Adina
        ///Adreanna
        ///Adriana
        ///Adrianna
        ///Adrianne
        ///Adrienne
        ///Aerona
        ///Afra
        ///Agatha
        ///Aggie
        ///Agnes
        ///Aida
        ///Aileen
        ///Aimee
        ///Aine
        ///Ainsley
        ///Aischa
        ///Aisha
        ///Aisling
        ///Ajlin
        ///Alaina
        ///Alana
        ///Alanis
        ///Alanna
        ///Alannah
        ///Alayah
        ///Alayna
        ///Alba
        ///Albertine
        ///Alea
        ///Aleah
        ///Alecia
        ///Aleisha
        ///Alejandra
        ///Aleksandra
        ///Alena
        ///Alessa
        ///Alessandra
        ///Alessia
        ///Alex
        ///Alexa
        ///Alexandra
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string femaleNames {
            get {
                return ResourceManager.GetString("femaleNames", resourceCulture);
            }
        }
    }
}
