//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe.Basics.Factions.Bugs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BugGeneratorFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BugGeneratorFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.Basics.Factions.Bugs.BugGeneratorFiles", typeof(BugGeneratorFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron
        ///Abdul
        ///Abdullah
        ///Abel
        ///Abraham
        ///Abram
        ///Abriel
        ///Ace
        ///Adam
        ///Adan
        ///Ade
        ///Aden
        ///Adnan
        ///Adrian
        ///Ahmad
        ///Ahmed
        ///Aidan
        ///Aiden
        ///Ainsley
        ///Al
        ///Alain
        ///Alan
        ///Alastair
        ///Albert
        ///Alberto
        ///Albie
        ///Alden
        ///Aldo
        ///Alec
        ///Alejandro
        ///Alen
        ///Alesandro
        ///Alex
        ///Alexander
        ///Alexis
        ///Alfie
        ///Alfonso
        ///Alfred
        ///Alfredo
        ///Ali
        ///Alistair
        ///Allan
        ///Allen
        ///Alonzo
        ///Aloysius
        ///Alphonso
        ///Alton
        ///Alvin
        ///Amari
        ///Amir
        ///Amit
        ///Amos
        ///Andre
        ///Andreas
        ///Andres
        ///Andrew
        ///Andy
        ///Angel
        ///Angelo
        ///Angus
        ///Anthony
        ///Anton
        ///Antonio
        ///Antony
        ///Aran
        ///Archer
        ///Archie
        ///Ari
        ///Arjun        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maleNames {
            get {
                return ResourceManager.GetString("maleNames", resourceCulture);
            }
        }
    }
}
